version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.Application"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.Core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.Features.BuilderAPI"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.Infrastructure"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.Tests"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.UI.API"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
  - package-ecosystem: "nuget"
    directory: "/src/MEVSharp.UI.CMD"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
