name: Docker Development
on:
  push:
    branches:
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Restore Dependencies
      working-directory: src
      run: dotnet restore MEVSharp.sln
    - name: Build
      working-directory: src
      run: dotnet build MEVSharp.sln --no-restore
    - name: Run Tests
      working-directory: src
      run: dotnet test MEVSharp.sln --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mevsharp/mevsharp:dev
