name: Tests
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Restore Dependencies
      working-directory: src
      run: dotnet restore MEVSharp.sln
    - name: Build
      working-directory: src
      run: dotnet build MEVSharp.sln --no-restore
    - name: Run Tests
      working-directory: src
      run: dotnet test MEVSharp.sln --no-build --verbosity normal
